### ISSUE TITLE
MW supplement fresh look, part 4: "rev" implementation

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/MWS#100] opened 2021-02-22 20:34 UTC
The steps to implement changes discussed in #97.
I'll try to do the changes in some kind of plausible sequence.
Also, I plan to change the copy [mwtranscode/mw.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/mw.txt) in this repository.  
When all changes have been made in the copy, then I'll update the 
production version at csl-orig/v02/mw/mw.txt.

**Comment by gasyoun** [comment] 2021-02-22 21:16
> When all changes have been made in the copy, then I'll update the
production version at csl-orig/v02/mw/mw.txt.

We stand silently behind.

**Comment by funderburkjim** [comment] 2021-02-22 21:33
## step0: 
Bring mwtranscode/mw.txt up to date with csl-orig/v02/mw/mw.txt.

Note: this is consistent with mwtranscode/mw_iast_AB_2a.txt  (after removal of comment lines).
[see comment](https://github.com/sanskrit-lexicon/MWS/issues/96#issuecomment-771177128)

See [this commit](https://github.com/sanskrit-lexicon/MWS/commit/fd1fe4f8419b0f0f37da6b1a3ba263fbfabfe22f) for mwtranscode/mw.txt differences.

## Also make mw_iast.txt consistent.
`python mw_transcode.py slp1 roman mw.txt mw_iast.txt`

See [this commit](https://github.com/sanskrit-lexicon/MWS/commit/990993bb603384734a4becb1b8a45a6201811415).

**Comment by funderburkjim** [comment] 2021-02-22 21:56
## step1  combine \<pb> and "rev"
Change mw_iast.txt by:
```'<pb n="1234,1"/><info n="rev"/>' ->   '<info n="rev" pc="1234,1"/>'```

See [the commit](https://github.com/sanskrit-lexicon/MWS/commit/d624e8b7c7f796eb5c6f802734a313ac9dd99eb6)

Make mw.txt consistent: `python mw_transcode.py roman slp1 mw_iast.txt temp_mw.txt`

See [commit](https://github.com/sanskrit-lexicon/MWS/commit/2dd4bb81b629299411d9021258adedd4921b93fc)

**Comment by Andhrabharati** [comment] 2021-02-23 03:26
> The steps to implement changes discussed in #97.
> I'll try to do the changes in some kind of plausible sequence.

I was waiting for this to happen.

> Also, I plan to change the copy [mwtranscode/mw.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/mw.txt) in this repository.
> When all changes have been made in the copy, then I'll update the
> production version at csl-orig/v02/mw/mw.txt.

I would rather suggest that the updating should be slightly differed.

Once the above "rev" blocks are duly reviewed, the "missed" entries part work should be taken up. As majority of them are about accents, they fall more as possible "rev"s, rather than "sup"s.

With that, all known "rev"s would have been considered as a lot.

These are somewhere near 50 or so, did not really count them, though listed them in the previous session. So should be done in a day or two, from my side and another day or two from @funderburkjim.

As the "sup" entries are quite many, we may take that they take more time to do, though they too could have some disguised "rev"s as noticed in these 7 parts. That can be called "sup" entry preparation & implementation phase.

**Comment by Andhrabharati** [comment] 2021-02-23 18:06
if @funderburkjim agrees for my above proposal, I might be able to give him the "missings" part file (just those portions with "BEG-END" tags), by the time he finishes reviewing the "rev"s; so that his work could be done at a continuous stretch.

**Comment by funderburkjim** [comment] 2021-02-23 18:24
I would prefer you NOT to modify further AB.3.1.txt - AB.3.7.txt.

However additional file(s) with  collections of BEGIN-END blocks sounds fine.  
So, go ahead with your proposal.

Suggest you make comments regarding additional changes in another issue.  
Let's reserve this issue to AB.3.1.txt - AB.3.7.txt.

**Comment by funderburkjim** [comment] 2021-02-23 18:28
## revdoc
I'll try putting some documentation of changes into the 'mwtranscode/revdoc' folder.

First entry is a 'status' file for the 194 BEGIN-END correction blocks present in AB.3.1.txt - AB.3.7.txt.

Currently, this just marks as 'DONE' the 50 blocks that AB classified as correctly done.  There were
a few additional such entries that

**Comment by Andhrabharati** [comment] 2021-02-23 19:48
> Suggest you make comments regarding additional changes in another issue.
> Let's reserve this issue to AB.3.1.txt - AB.3.7.txt.

Sure; opened another issue #101, as suggested.

**Comment by funderburkjim** [comment] 2021-02-26 22:35
## changes derived from AB_3.1 -3.7
See the changes at [a93142c commit](https://github.com/sanskrit-lexicon/MWS/commit/a9d142cc62181aed6203412c9e3651f701e99112).

All in all, 435 lines of mw_iast.txt are changed, 30 lines were deleted, and 21 lines inserted.

Changes were based on material from AB as collected in mwtranscode/revdoc directory:
* [AB.3.1-7.status.md](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/AB.3.1-7.status.md)
* [comments_edit.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/comments_edit.txt) and the sister emacs org mode file
* [readme_added_comments.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/comments_edit.txt) and the sister emacs org mode file.

The two '.org' files are best viewed locally with Emacs editor.  The '.txt' files are for non-Emacs users.

**Comment by Andhrabharati** [comment] 2021-02-27 02:37
> There are 4 corrections that have not been handled -- They've
> stumped me thus far. Noted with '?'

Just a quick look at the ? entries-
* DONE 002 aṃsadhrī TYPO ?
 yes, the accents might have to be removed in the HW.
 
 * TODO 016 adhīvāsa ?
To revert ([`<ls>RV.</ls>; <ls>ŚBr.</ls>; <ls>MBh.</ls> &c.`]) to ([`<ls>RV.</ls>; <ls>ŚBr.</ls> &c`.])

* DONE 097 ṛjūya ?
What's the doubt here?

* TODO 177 mamat ?
What's the doubt here?

**Comment by Andhrabharati** [comment] 2021-02-27 02:43
Will have a look at the rest leisurely, to "see" the details.

**Comment by Andhrabharati** [comment] 2021-02-27 13:22
I could glean through the files from @funderburkjim and here are my comments-

; jim: Use preformed á rather than combining accent á
;; AB: still there are 19 occurrences of combining accent á in the file.

; Jim: removed accent aṅguli—saṃdeśa  per Annexure for this compound
;; AB: glad to see this pointed out. I've overlooked it.

 ; jim also remove accent over 'u' per ANNEX
;; AB: Though I've remarked about the accent change missing, I myself did not do it (at ú) in the <Ls>, though corrected it at ā́.

;; jim: also put <info n="rev" pc="1331,2"/>
;; AB: I missed mentioning this marking, though the entry discussion started with a R(1331,2)!

Finally, it is not clear if Jim has "considered" my remark that the comp. words under a HW having accent change done should also be marked for the accent change.
[There are few entries thus indicated in the list].

**Comment by Andhrabharati** [comment] 2021-02-27 13:24
It appears that the 4 entries marked with ? are left (by Jim), as they posed a major change in my discussion- not just for the accent change and ls-removal (as I quickly responded).

**Comment by Andhrabharati** [comment] 2021-02-27 13:55
> Currently, this just marks as 'DONE' the 50 blocks that AB classified as correctly done. There were
> a few similar entries that need attention and that are not marked DONE.
> Refer: AB.3.1-7.status.md

Just re-looked at these entries, wherein @funderburkjim assumed that AB might've marked them correctly.

Found three entries that were wrongly "marked" by me earlier.

The corrected ones are as under-

```
;; BEGIN
<L>52<pc>1,2<k1>aṃśu<k2>aṃśú<e>1A	¦ a ray, sunbeam <info n="rev" pc="1308,1"/><info lex="inh"/>	<LEND>
;; R(1308,1) aṃśu (col. 2, l. 1, for ‘array’ read ‘a ray’)
;; The accent change in HW needs to be done in these HW entries (L-47 onwards).

;; BEGIN
<L>1013<pc>5,2<k1>agnibhūti<k2>agní—bhūti<e>3	<s>agní—bhūti</s>	¦ <lex>m.</lex> <ab>N.</ab> of one of the eleven chief pupils (<s1 slp1="gaRaDara">gaṇadhara</s1>s) of the last <s1 slp1="tIrTakara">Tīrthakara</s1>. (see also, <ls>Pāṇ. 8-2, 107, </ls><ab>Vārtt.</ab> 2, <ls>Pat.</ls>) <info n="rev" pc="1309,1"/><info lex="m"/>	<LEND>
;; R(1309,1) agni-bhūti (see also Pāṇ. viii, 2, 107, Vārtt. 2, Pat.)
;; The accent change in HW needs to be done here.

;; BEGIN
<L>13702<pc>79,3<k1>abhramāṃsī<k2>abhrá—māṃsī<e>3	<s>abhrá—māṃsī</s>	¦ <lex>f.</lex> the plant <bot>Valeriana</bot> <s1 slp1="jawAmAMsI">Jaṭāmāṉsī</s1>, <ls>L.</ls> <info n="rev" pc="1315,3"/><info lex="f"/>	<LEND>
;; R(1315,3) -maṃsī (read -māṃsī); comp. word header "abhra (in comp.)" [no accent]
;; The accent change in HW needs to be done here.
```

Jim may pl. correct these listed above.

**Comment by Andhrabharati** [comment] 2021-02-27 14:44
> All in all, 435 lines of mw_iast.txt are changed, 30 lines were deleted, and 21 lines inserted.

Just about 500 entries' corrections needed ~4 man-weeks' time!! (12 days, two persons so far)

**Comment by funderburkjim** [comment] 2021-02-27 18:43
Revised mw_iast.txt based on AB comments above.
The revisions are being done by a programmatic application of a 'change' file to the prior version.
Thus, the change file is a good way to review whether some change has or has not been made.
The change file at this point in time is [revdoc/changes_1.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/changes_1.txt).

Here is a summary of the revisions:
1.  Replaced remaining combining accent á with preformed á; there are now no combining
     accent á in mw_iast.txt.
2. re:  `the comp. words under a HW having accent change done should also be marked for the accent change.`  -- I did address this issue.  Please see the changes_1.txt file to see if you
notice any that I missed.  
   * Also see section 'additional simple changes' in 
[readme_added_comments.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwtranscode/revdoc/readme_added_comments.txt)
3. Replace aṃśú with aṃśu for all L=47-78
4. remove accent at L=1013, agnibhūti
5. remove accent at L=13702,abhramāṃsī

**Comment by gasyoun** [comment] 2021-02-27 18:52
> Replaced remaining combining accent á with preformed á; there are now no combining
accent á in mw_iast.txt.

Hope it does not affect the search. In browser preformed accents via Ctrl + F are harder to find.

**Comment by Andhrabharati** [comment] 2021-02-27 19:23
> > Replaced remaining combining accent á with preformed á; there are now no combining
> > accent á in mw_iast.txt.
> 
> Hope it does not affect the search. In browser preformed accents via Ctrl + F are harder to find.

As I understand, the search is done on k1 fields having no accents.

**Comment by gasyoun** [comment] 2021-02-28 06:52
> As I understand, the search is done on k1 fields having no accents.

Not in browser, when we will have static pages. But not a critical issues, because the static pages are a byproduct.

**Comment by funderburkjim** [comment] 2021-02-28 23:19
>  search on k1 fields having no accents.

Yes.  But you Can put in accents (for example agní) in simple search.
  (with input=simple, and input_default=default)
simple-search also detects Devanagari and iast.

**Comment by Andhrabharati** [comment] 2021-03-01 16:03
>     Please see the changes_1.txt file to see if you
>         notice any that I missed.

**Finding quite many, though not specifically limited to comp. word accent changes.**

But I am not looking at the **changes_1** file (as it looked too much splitted, and stripped of my earlier remarks); instead using the **comments_edit** file (containing all the info required)..

Hopefully should be able to post the final results before my retiring tonight.

**Comment by Andhrabharati** [comment] 2021-03-01 18:28
**Successfully finished going through all the entries again.**

The remarked files are posted at revdoc folder as
- comments_edit (3.1-3.7)-AB remarks.txt and
- readme_added_comments-AB remarks.txt

As marked in these two files-
- there are some corrections remained to be done **NOW** and
- many to be stored somewhere as TODO items sometime later.

On the whole, it appears that Jim has taken almost all my suggestions.

**Comment by gasyoun** [comment] 2021-03-01 20:35
> On the whole, it appears that Jim has taken almost all my suggestions.

Oh, it was a short, but intensive trip even to look at.

**Comment by funderburkjim** [comment] 2021-03-03 21:51
Re ākenipa (L=22292 and 93),
Here are what @Andhrabharati suggests for revision:
```
22292:
<s>āké—nipá</s> ¦ <lex>mfn.</lex> (said of the horses of the <s1 slp1="aSvin">Aśvin</s1>s) protecting in the vicinity, <s>ā kenipā́so</s>, <ab>ib.</ab> <ls>iv, 45, 6</ls> <info n="rev" pc="1319,1"/><info lex="m:f:n"/>
22293:
<s>āké—nipá</s> ¦ <lex>mfn.</lex> (said of the horses of the <s1 slp1="aSvin">Aśvin</s1>s) protecting in the vicinity, <s>ā kenipā́so</s>, <ab>ib.</ab> <ls>iv, 45, 6</ls> <info n="rev" pc="1319,1"/><info lex="m:f:n"/>
```
I think that 22292 should be slightly different in the reference:
`<ab>ib.</ab> <ls>iv, 45, 6</ls>` -> `<ls>RV. iv, 45, 6</ls>`

Otherwise, the 'ib.' is unresolved.
@Andhrabharati Agree?

**Comment by funderburkjim** [comment] 2021-03-03 23:20
Re kadru.
L=42901 and 42902  (248,1-2;  1323,3)
AB revision:
```
<L>42901<pc>248,1<k1>kadrū<k2>kádrū́<e>1B
<s>kádrū́</s> ¦ <lex>f.</lex> a particular divine personification (described in certain legends which relate to the bringing down of the <s1 slp1="soma">Soma</s1> from heaven <pb n="248,2"/>; according to the <s1 slp1="brAhmaRa">Brāhmaṇa</s1>s, ‘the earth personified’), <ls>TS. vi</ls>; <ls>ŚBr. iii, vi</ls>; <ls>Kāṭh.</ls> &c.<info lex="f"/>

<L>42902<pc>248,2<k1>kadrū<k2>kádrū́<e>1B
¦ <ab>N.</ab> of a plant (?). <info lex="inh"/>
```
I suggest slightly different:
```
<L>42901<pc>248,1<k1>kadru<k2>kadrū́<e>1B
<s>kadrū́</s> ¦ <lex>f.</lex> a particular divine personification (described in certain legends which relate to the bringing down of the <s1 slp1="soma">Soma</s1> from heaven <pb n="248,2"/>; according to the <s1 slp1="brAhmaRa">Brāhmaṇa</s1>s, ‘the earth personified’), <ls>TS. vi</ls>; <ls>ŚBr. iii, vi</ls>; <ls>Kāṭh.</ls>; <ls>RV.</ls> &c.<info n="rev" pc="1323,3"/><info lex="f"/>

<L>42902<pc>248,2<k1>kadru<k2>kádru<e>1B
¦ <ab>N.</ab> of a plant (?). <info lex="inh"/>
```

@Andhrabharati  Agree?


```

**Comment by funderburkjim** [comment] 2021-03-03 23:56
Re: L=65948, k1=gupti, pc=359,1 1326,2

ACCENT changes from gúpti to gupti L=65945-65954

I made these changes.  

BUT  I am queasy about the reasoning.
The entry at p. 359,1 shows an accent: gúpti

![image](https://user-images.githubusercontent.com/6393033/109888510-a35e6600-7c51-11eb-81c5-0dbfef401c56.png)


In the Supplement at p. 1326,2 gupti appears without an accent.

![image](https://user-images.githubusercontent.com/6393033/109888626-c426bb80-7c51-11eb-8acd-5b50cacfd764.png)

Is it valid to infer from the author's supplement entry  that gupti in the body of the text should appear without an accent?

**Comment by funderburkjim** [comment] 2021-03-04 02:35
>  L=129737, k1=pnā, pc=652,2   

AB suggested to revise to ptā.   This was done previously.

**Comment by funderburkjim** [comment] 2021-03-04 02:45
>  L=133755, k1=pratardana, pc=674,2 
   \<s>pra-°tardana<\/s> ¦ \<lex>m.\</lex> \<ab>N.\</ab> of a king 

AB: `Wherefrom the ° got into <s>pra-°tárdana</s>? Needs to be removed.`

Disagree.  This `°` indicates that the word is related (as a verbal derivative?) from `pratṛd` (as opposed to
being a samAsa from pratṛd).  

It might be better to get rid of the '-'  e.g. to have `pra°tárdana` instead of `pra-°tárdana`.

**Comment by funderburkjim** [comment] 2021-03-04 03:31
```
L=153876.1, k1=ma, pc=771,2
...
;; As such, it should be placed the beginning of 4. mā entry (L-153876.1), not at the ending (L-153890). (Wonder how the new HW is given a .x L-number!!)
AB: Would Jim not owe me a reply to this .1 L-number here? (This is not a new insertion from Annexure to have some "vague number" to be allotted.)
```

This is the reason:
```
; We try to (a) maintain L-numbers over time; and also (b) maintain
; increasing values of L-numbers within mw.txt.
; For various reasons such as inserting 'sup' records, we must manufacture
; a new L-number while maintaining (b).
```

In the ma-case, we needed to move an entry to just before 153877.
The entry before L=153877 was 153876.
Thus, we need an L-number between 153876 and 153877.  I happened to choose 153876.1.

Does this explain?

**Comment by Andhrabharati** [comment] 2021-03-04 08:56
> 
> 
> Re ākenipa (L=22292 and 93),
> 
> I think that 22292 should be slightly different in the reference:
> `<ab>ib.</ab> <ls>iv, 45, 6</ls>` -> `<ls>RV. iv, 45, 6</ls>`
> 
> Otherwise, the 'ib.' is unresolved.
> @Andhrabharati Agree?

Naigh. references are not with the 3 level numbers as are RV numbers anywhere in the text.
So, replacing the ib. with RV. looks to be correct.

**Comment by Andhrabharati** [comment] 2021-03-04 09:07
> 
> 
> Re kadru.
> L=42901 and 42902 (248,1-2; 1323,3)
> AB revision:
> 
> ```
> <L>42901<pc>248,1<k1>kadrū<k2>kádrū́<e>1B
> <s>kádrū́</s> ¦ <lex>f.</lex> a particular divine personification (described in certain legends which relate to the bringing down of the <s1 slp1="soma">Soma</s1> from heaven <pb n="248,2"/>; according to the <s1 slp1="brAhmaRa">Brāhmaṇa</s1>s, ‘the earth personified’), <ls>TS. vi</ls>; <ls>ŚBr. iii, vi</ls>; <ls>Kāṭh.</ls> &c.<info lex="f"/>
> 
> <L>42902<pc>248,2<k1>kadrū<k2>kádrū́<e>1B
> ¦ <ab>N.</ab> of a plant (?). <info lex="inh"/>
> ```
> 
> I suggest slightly different:
> 
> ```
> <L>42901<pc>248,1<k1>kadru<k2>kadrū́<e>1B
> <s>kadrū́</s> ¦ <lex>f.</lex> a particular divine personification (described in certain legends which relate to the bringing down of the <s1 slp1="soma">Soma</s1> from heaven <pb n="248,2"/>; according to the <s1 slp1="brAhmaRa">Brāhmaṇa</s1>s, ‘the earth personified’), <ls>TS. vi</ls>; <ls>ŚBr. iii, vi</ls>; <ls>Kāṭh.</ls>; <ls>RV.</ls> &c.<info n="rev" pc="1323,3"/><info lex="f"/>
> 
> <L>42902<pc>248,2<k1>kadru<k2>kádru<e>1B
> ¦ <ab>N.</ab> of a plant (?). <info lex="inh"/>
> ```
> 
> @Andhrabharati Agree?
> 
> ```
> 
> ```

I have no reason to disagree.
But the RV. ref. should be placed first in the list of `<ls>` items, as per the book's chrono order.

**Comment by Andhrabharati** [comment] 2021-03-04 09:10
> 
> Is it valid to infer from the author's supplement entry that gupti in the body of the text should appear without an accent?

I guess so; Every instance where an accent changed is involved/intended, it is shown in the annexure clearly.
If the gupti is to be with the accent, I think they would have showed it so in the annexure.

**Comment by Andhrabharati** [comment] 2021-03-04 09:16
> 
> 
> > L=133755, k1=pratardana, pc=674,2
> > <s>pra-°tardana</s> ¦ <lex>m.</lex> <ab>N.</ab> of a king
> 
> AB: `Wherefrom the ° got into <s>pra-°tárdana</s>? Needs to be removed.`
> 
> Disagree. This `°` indicates that the word is related (as a verbal derivative?) from `pratṛd` (as opposed to
> being a samAsa from pratṛd).
> 
> It might be better to get rid of the '-' e.g. to have `pra°tárdana` instead of `pra-°tárdana`.

JIm's point seems correct, looking into the Main page entries.
We can consider the - as a typo (in the book) for °. [one of those rare cases!!]

**Comment by Andhrabharati** [comment] 2021-03-04 09:35
> 
> In the ma-case, we needed to move an entry to just before 153877.
> The entry before L=153877 was 153876.
> Thus, we need an L-number between 153876 and 153877. I happened to choose 153876.1.
> 
> Does this explain?

Very well explains the ad-hoc logic that I've been saying all along!! [**Do my words sound harsh?; but I had to use them thus to show my feeling.**]

That other entry that was moved should've been with 153877 (being the first record for the HW) and the next one could've been 153877.1 (being the continuation of the above).

Speaking of this simple numbering rule of L-records (**to be in increasing order**) when new insertions happen, now I think we can go ahead with the missed comp. word headers in the annexure pages. 

Seen that there even 3 decimal numbered L-records (8 of them); it's so easy to give those ad-hoc numbers for those new ones (**with infinite ways to allot the "increasing ordered" numbers**). **Not at all that difficult, as @funderburkjim mentioned elsewhere (#101)- reproduced below.**

> Based only on a cursory look at 'missed comp. word headers' list. it seems that these will be
> "sup" items that are relatively easy to do, with the hardest part will be deciding what L-number to give them.

**Comment by gasyoun** [comment] 2021-03-04 11:16
> If the gupti is to be with the accent, I think they would have showed it so in the annexure.

Agree.

**Comment by funderburkjim** [comment] 2021-03-04 19:25
> But the RV. ref. should be placed first in the list of <ls> items, as per the book's chrono order.

Revised as per:
```
<s>kadrū́</s> ¦ <lex>f.</lex> a particular divine personification (described in certain legends which relate to the bringing down of the <s1 slp1="soma">Soma</s1> from heaven <pb n="248,2"/>; according to the <s1 slp1="brAhmaRa">Brāhmaṇa</s1>s, ‘the earth personified’), <ls>RV.</ls>; <ls>TS. vi</ls>; <ls>ŚBr. iii, vi</ls>; <ls>Kāṭh.</ls> &c.<info n="rev" pc="1323,3"/><info lex="f"/>
```

The 'book chrono order' for literary source references -- a new insight to me re MW!

**Comment by Andhrabharati** [comment] 2021-03-04 19:54
> The 'book chrono order' for literary source references -- a new insight to me re MW!

The first sentence of Introduction p. xviii, kind of 'indicates' this ordering.

And one can see that the same has been followed, by (carefully) looking at the `<ls>` order, at various entries in the book.
(Of course there could be some exceptions; but that's how the majority, if not all, entries are having it.)

**Comment by funderburkjim** [comment] 2021-03-04 20:08
```
kaca
;; jim  Syntax for 'local abbreviation' <ab n="note">n.</ab>
AB: Why only some are locally expanded and some are not?
```

Frequently used abbreviations are noted as `<ab>cf.</ab>`, and the abbreviation 'expansion' is
as specified in [mwab_input.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/mw/pywork/mwab/mwab_input.txt).

Occasional 'ad-hoc' abbreviation expansions are as `<ab n="note">n.</ab>`.   In this particular case,
`n.`  the reason for the local-abbreviation-expansion is to override the usual meaning of 'n.',
which is `neuter gender`.    Further, usually 'n.' is used in a `<lex>` tag, and the mwab_input.txt file
is also used in displays to provide an expansion of the genders in lex tag.

**Comment by Andhrabharati** [comment] 2021-03-04 20:13
Understood; but <lex>n.</lex> and <ab>n.</ab> would definitely be distinguishable, isn't it?

**Comment by funderburkjim** [comment] 2021-03-04 20:21
You're asking a detail about the display code.  As currently written, the display code would get 
the expansion tooltip for both `<lex>n.</lex> and <ab>n.</ab>` from the same place (mwab_input.txt);
so, as far as tooltips go, both these would show tooltips as 'neuter gender'.

However, the display code for `<ab n="note">n.</ab>`  notices the 'n' attribute of 'ab' is present,
and uses the value of that 'n' attribute  (namely 'note') as the tooltip.

**Comment by Andhrabharati** [comment] 2021-03-04 20:47
But just checked that `<ls>A.</ls>` and `<ab>A.</ab>` are distinguished, for tool-tips.

Anyway, as I mentioned elsewhere, I don't want to know much about this tagging.
Would leave it to you to handle wherever required, in my corrections/suggestions being sent.

**Comment by funderburkjim** [comment] 2021-03-04 21:22
```
; Add accent for compounds of pAtra: L=120810-120840  
; pātr -> pā́tr
```

**Comment by Andhrabharati** [comment] 2021-03-08 05:41
We can close this issue now, with a note that "the points identified to be considered yet" are put in a TODO list.

**Closed by Andhrabharati** 2021-03-08 05:41 UTC
