### ISSUE TITLE
Miscellaneous corrections

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/MWS#137] opened 2022-07-23 09:37 UTC
**quote marks:**

- `'e<srs/>hi mā yāsīr!'` to be changed as `‘e<srs/>hi mā yāsīr!’`
- ``the esoteric`` to be changed as `‘the esoteric’`
- ``first father``' to be changed as `‘first father’`
- `‘perhaps it is and is not and is not expressible in words'` to be changed as  `‘perhaps it is and is not and is not expressible in words’`
- `‘a ‘goat’, a derivation in the sense of, goat's flesh’` to be changed as `‘a goat’, a derivation in the sense of ‘goat's flesh’`
- `‘the ‘<s1>Śabara</s1>s’ food’` to be changed as `‘the <s1>Śabara</s1>s' food’`

**apostrophe:**

- `<s>-gate' hani</s>` to be changed as `<s>-gate 'hani</s>`
- `60 years ' cycle` to be changed as `60 years' cycle`

**multiplication mark:**

- the x (U+0078) at 1 instance of `[0-9]x [0-9]` and 121 instances of `[0-9] x [0-9]` could be changed as the multiplication mark × (U+00D7).

**prosody marking:**

- `(- - u u - -)` to be changed as `(- - ˘ ˘ - -)`

**miscellaneous:**

- 1880 instances of space at the line-ending to be deleted.
- 1 instance of \t (tab) at the line-ending to be deleted.
- 2 instances of * to be deleted.
- 1 instance of ** to be deleted.

**Comment by Andhrabharati** [comment] 2022-07-23 14:19
**number followed by letter:**

`0f` to be changed as `of`
`0law-book` to be changed as `law-book`
`3oth` to be changed as `30th`
`4<s1` to be changed as `4 <s1`
`4tb` to be changed as `4th`
`5<s1` to be changed as `5 <s1`
`5jewels` to be changed as `5 jewels`
`6o` to be changed as `60`
`11sth` to be changed as `11th` [2 places]
`p.802col.2` to be changed as `p.802 col.2`
`p.1118col.1.` to be changed as `p.1118 col.1.`
`p.1200col.3.` to be changed as` p.1200 col.3.`

**Comment by Andhrabharati** [comment] 2022-07-24 18:04
`missing space before '=':`
  (62609): `some=`
  (95618): `<s>-liliśire</s>)=`
(100550): `<ls>AV.</ls>= ‘diarrhoea’.`
(195423): `Kollam 336=`
(511483): `(also)= <s>bhū</s>`
(686740): `<ab>mfn.</ab>= <s>°vat</s>`
(769991): `<s>sana</s>=`

**Comment by Andhrabharati** [comment] 2022-07-29 17:12
Mis-matched pairing of [...] :

(38354):	`, <ls>Pāṇ.</ls>]`	` [<ls>Pāṇ.</ls>]`
(85683):	`[<ls>L.</ls>`	`[<ls>L.</ls>]`
(85686):	`[<ls>L.</ls>`	`[<ls>L.</ls>]`
(85689):	`[<ls>L.</ls>`	`[<ls>L.</ls>]`
(169602):	`<s>dhuni</s>, j`	`<s>dhuni</s>]`

**Comment by Andhrabharati** [comment] 2022-07-29 19:04
Mis-matched pairing of (...) :

(15609):	`<s>-devatā</s>)`	`<s>-devatā</s>`
(15612):	`<s>-devatā</s>)`	`<s>-devatā</s>`
(29427):	`([<ls>MaitrS.</ls>; <ls>VS.</ls>]`	`[<ls>MaitrS.</ls>; <ls>VS.</ls>]`
(29430):	`([<ls>MaitrS.</ls>; <ls>VS.</ls>]`	`[<ls>MaitrS.</ls>; <ls>VS.</ls>]`
(40536):	`<s>-pūrvaka</s>)`	`<s>-pūrvaka</s>`
(40545):	`<s>-pūrvaka</s>)`	`<s>-pūrvaka</s>`
(41022):	`[<ls>RV. x, 152, 2</ls>; <ls>AV.</ls> &c.]) ([<ls>ŚBr.</ls>]`	`[<ls>RV. x, 152, 2</ls>; <ls>AV.</ls> &c.] [<ls>ŚBr.</ls>]`
(41025):	`[<ls>RV. x, 152, 2</ls>; <ls>AV.</ls> &c.]) ([<ls>ŚBr.</ls>]`	`[<ls>RV. x, 152, 2</ls>; <ls>AV.</ls> &c.] [<ls>ŚBr.</ls>]`
(95025):	`<ab>B.</ab>)`	`(<ab>B.</ab>)`
(100964):	`(<s>ās</s> ¦`	`¦`	; this is a word ending, mostly being 'removed' throughout
(114152):	`<ls>Ragh.</ls>)`	`<ls>Ragh.</ls>`	; print correction
(131776):	`(<ab>B.</ab>`	`(<ab>B.</ab>)`
(275105):	`(? for <s>dhaṅka-m</s>`	`(? for <s>dhaṅka-m°</s>)`
(290174):	`a) kind of drama`	`a kind of drama`
(312310):	`(<ls n="MBh.">ii, 983</ls>-<ls n="MBh.">1203</ls>`	`(<ls n="MBh.">ii, 983</ls>-<ls n="MBh.">1203</ls>)`
(378395):	`or <s>°lā<srs/>bda</s>`	`(or <s>°lā<srs/>bda</s>`
(378395):	`(which begins on the 20th October, <ab>A.D.</ab> 879.`	`(which begins on the 20th October, <ab>A.D.</ab> 879.)`
(378398):	`or <s>°lā<srs/>bda</s>`	`(or <s>°lā<srs/>bda</s>`
(378398):	`(which begins on the 20th October, <ab>A.D.</ab> 879.`	`(which begins on the 20th October, <ab>A.D.</ab> 879.)`
(378401):	`or <s>°lā<srs/>bda</s>`	`(or <s>°lā<srs/>bda</s>`
(378401):	`(which begins on the 20th October, <ab>A.D.</ab> 879.`	`(which begins on the 20th October, <ab>A.D.</ab> 879.)`
(436419):	`<ab>wk.</ab>)`	`<ab>wk.</ab>`
(467381):	`<ab n="praise">pr°</ab>’`	`<ab n="praise">pr°</ab>’)`
(544670):	`(<ls>HPariś.</ls>`	`(<ls>HPariś.</ls>)`
(544673):	`<lex>n.</lex>)`	`<lex>n.</lex>`
(690877):	`(<ab>Sch.</ab>`	`(<ab>Sch.</ab>)`
(714228):	`<ab n="Germany">G°</ab>)`	`<ab n="Germany">G°</ab>`
(821440):	` <ls>RV. x, 133</ls>`	 `<ls>RV. x, 133</ls>)`

**Comment by Andhrabharati** [comment] 2022-08-06 06:18
### Issues crept into temp_mw_3_iast, not in the prev. temp_mw_6_iast

 1. space before ';'

(204651):
¦ inserted, interpolated, `<ls>R. ii, <ab>ch.</ab> 96</ls> <ab>Sch.</ab>; <ls>Naiṣ. xxii, 48</ls> <ab>Sch.</ab><info lex="inh"/>`
has become
¦ inserted, interpolated, ; -------------------------------------------------------

**all the missed matter after the comma is to be filled up!**

(516867):
`<lex>f.</lex>` (A.)
has become
`<lex>f.</lex>` (`<ls>A.</ls> ;[Apte dictionary]`)

**` ;[Apte dictionary]` to be removed which was my comment**

 2. space before ')'
 3. 
(144769): 
`<ab>Gr.</ab> 969)`
has become
`<ls>Gr. 969</ls> )`

**space to be deleted before the closing brace.**

**Comment by Andhrabharati** [comment] 2022-08-06 16:06
### Root symbol (√) and `<s>` tag:

There are 4625 `√ <s>` instances and 360 `<s>√  ` instances.

Should all be with same seq, √  preceding (outside) or following (inside) the `<s>` tag?

As there are cases of type `√ <hom>1.</hom> <s>`, we can conclude that it should always precede.

**Comment by Andhrabharati** [comment] 2022-08-06 16:37
**Capital letter in a tagged entry, where it shouldn't be so:**

(265210): `<i>jallālu 'ddIn</i>`	`<i>jallālu 'ddīn</i>`
(269458): `<etym>gIvēnu</etym>`	`<etym>gīvēnu</etym>`
(300555): `<s1>YamaYamī</s1>`	`<s1>Yama-Yamī</s1>`
(303738): `<s1>ŚrI</s1>`	`<s1>Śrī</s1>`
(328281): `<s1>LakṣmI</s1>`	`<s1>Lakṣmī</s1>`
(328284): `<s1>LakṣmI</s1>`	`<s1>Lakṣmī</s1>`
(476884): `<etym>fSu</etym>`	`<etym>fshu</etym>`
(585671): `<etym>rathaestA</etym>`	`<etym>rathaestā</etym>`
(585677): `<etym>rathaestA</etym>`	`<etym>rathaestā</etym>`
(628613): `<etym>virSús</etym>`	`<etym>virshùs</etym>`

**Comment by Andhrabharati** [comment] 2022-08-08 06:22
**Number before a `<s>` tag, either indicating a missing `<hom>` tag or a typo:**

`[0-9] <s>`
(60681):  `1 <s>ali</s>`	`<hom>1.</hom> <s>ali</s>`
(227757): `2 <s>gir</s>`	`<hom>2.</hom> <s>gir</s>`
(227757): `2 <s>gīrṇá</s>`	`<hom>2.</hom> <s>gīrṇá</s>`
(249605): `1. 2. 3 <s>cit</s>`	`<hom>1.</hom> <hom>2.</hom> >hom>3.</hom> <s>cit</s>`
(352745): `1. and 2 <s>navya</s>`	`<hom>1.</hom> and <hom>2.</hom> <s>navya</s>`
(353175): `2 <s>-áka</s>`	`<hom>2.</hom> <s>-áka</s>`
(441714): `1 <s>mi</s>`	`<hom>1.</hom> <s>mi</s>`
(469506): `1 <s>prā<srs/>ṅ-nyāya</s>`	`<hom>1.</hom> <s>prā<srs/>ṅ-nyāya</s>`
`-------------------`

`[0-9], <s>`
(65237): `4, <s>liyat</s>	`<s>-līyat</s>
(205493): `2, <s>kṣúdh</s>`	`<hom>2.</hom> <s>kṣúdh</s>`
(357525): `1, <s>náva</s>`	`<hom>1.</hom> <s>náva</s>`
(415453): `2, <s>pat</s>`	`2, <ls>Pat.</ls>`
(419111): `2, <s>as</s>`	`<hom>2.</hom> <s>as</s>`
(425563): `1. and 2, <s>puri</s>`	`<hom>1.</hom> and <hom>2.</hom> <s>puri</s>`
(464659): `1, <s>si</s>`	`<hom>1.</hom> <s>si</s>`
(475781): `5, <s>i</s>`	`<hom>5.</hom> <s>i</s>`
(507691): `1, <s>bhī</s>`	`<hom>1.</hom> <s>bhī</s>`
(555959): `1, <s>mura</s>`	`<hom>1.</hom> <s>mura</s>`
(665267): `1, <s>ru</s>`	`<hom>1.</hom> <s>ru</s>`
(708977): `2, <s>śad</s>`	`<hom>2.</hom> <s>śad</s>`
(752772): `1. 2, <s>vṛ</s>`	`<hom>1.</hom> <hom>2.</hom> <s>vṛ</s>`
(753242): `2, <s>saṃ-vedya</s>`	`<hom>2.</hom> <s>saṃ-vedya</s>`
(791067): `7, <s>sa</s>`	`<hom>7.</hom> <s>sa</s>`
(801680): `7, <s>sa</s>`	`<hom>7.</hom> <s>sa</s>`
(803606): `1, <s>sam-udra</s>`	`<hom>1.</hom> <s>sam-udra</s>`
`-------------------`

`[0-9]\. <s>`
(7485): `1. <s>ajá</s>`	`<hom>1.</hom> <s>ajá</s>`
(7485): `1. <s>ajana</s>`	`<hom>1.</hom> <s>ajana</s>`
(12602): `1. <s>kṛ</s>`	`<hom>1.</hom> <s>kṛ</s>`
(13338): `3. <s>á-diti</s>	``<hom>3.</hom> <s>á-diti</s>`

**... LIST CONTINUES (~600 lines to check manually)**
`-------------------`

[0-9]: <s>
(35207): `1: <s>kṛ</s>`	`<hom>1.</hom> <s>kṛ</s>`

**Comment by funderburkjim** [comment] 2022-08-28 18:34
## correction/change work done.

About 13000+ lines were altered.

The work was done in the [issue137 directory](https://github.com/sanskrit-lexicon/MWS/tree/master/mwsissues/issue137).

I aimed to include all the items mentioned by Andhrabharati.
In addition, several additional changes were made with the objective of bring certain details of
the digitization into better conformity with the printed text.  No doubt there are other similar changes that will be made as such differences are noticed.

## punctuation at end of quoted text.
This is one instance where I think there is a good reason for the digitization to vary from the printed text.   The printed text invariably puts punctuation (comma, period, semicolon) BEFORE (inside) the closing quote of quoted text. But I have changed to uniformly put the punctuation AFTER (outside) the closing quote: For instance:
```
OLD  (agrees with print):
<s>aMSu—Dara</s> ¦ <lex>m.</lex> ‘bearer of rays,’ the sun, <ls>L.</ls>
NEW
<s>aMSu—Dara</s> ¦ <lex>m.</lex> ‘bearer of rays’, the sun, <ls>L.</ls>
```
The reason for the change is that the ending comma, etc. is *not part of the quote*, but rather separates the quote from other semantic chunks.
Note: in case of period, there are a very small number of cases where an ending period IS part of the quoted text, and has thus been left inside, for examples:
```
[The title <s>AcArya</s> affixed to names of learned men is rather like our ‘Dr.’; <ab>e.g.</ab> <s>rAGavA<srs/>cArya</s>, &c.]

**Comment by funderburkjim** [comment] 2022-08-28 18:37
## iast version 
This is consistent with the slp1 commit of csl-orig/v02/mw.txt.

[temp_mw_issue137_iast.zip](https://github.com/sanskrit-lexicon/MWS/files/9440250/temp_mw_issue137_iast.zip)

**Comment by funderburkjim** [comment] 2022-08-28 18:41
## next 
Before closing this issue, I'll wait a couple of days to deal with errors or omissions in the way I handled the mw cleanup items of this issue.

My intention then is to take a break from mw changes,
and return attention to the ongoing ls-cleanup of PW and PWG.

**Comment by gasyoun** [comment] 2022-08-29 18:26
> (- - u u - -) to be changed as (- - ˘ ˘ - -)

@Andhrabharati sure?

**Comment by gasyoun** [comment] 2022-08-29 18:28
>  The printed text invariably puts punctuation (comma, period, semicolon) BEFORE (inside) the closing quote of quoted text. But I have changed to uniformly put the punctuation AFTER (outside) the closing quote

@funderburkjim can we document it in a .txt readme, not to forget where there is a such CHANGE by intention?

**Comment by funderburkjim** [comment] 2022-08-30 03:29
## error correction
Discovered two errors, and corrected.  See 'correct two errors. modify change_5.txt' section of
[issue137 readme.txt](https://github.com/sanskrit-lexicon/MWS/blob/master/mwsissues/issue137/readme.txt) for details.

Also revised iast version:
[temp_mw_issue137_iast_rev.zip](https://github.com/sanskrit-lexicon/MWS/files/9449331/temp_mw_issue137_iast_rev.zip)

**Comment by funderburkjim** [comment] 2022-08-30 03:31
> Can we document the intentional change?

A note was made in mw_printchange.txt file of csl-corrections repository: https://github.com/sanskrit-lexicon/csl-corrections/commit/b7ccd24d1988e8cda9105adcd18eda3d1c9ba1b0

**Comment by funderburkjim** [comment] 2022-08-30 03:40
> (- - u u - -) to be changed as (- - ˘ ˘ - -)

This occurs under `<L>82334<pc>435,3<k1>tanumaDyA`

This note from readme.txt of issue137:
```
NOTE:
1. (- - u u - -) to be changed as (- - ˘ ˘ - -)
  Instead change to (¯ ¯ ˘ ˘ ¯ ¯), as used 48 times elsewhere for meter
 i.e., I used the unicode macron (\u00af) for long.
```

**Comment by Andhrabharati** [comment] 2022-08-30 18:18
@funderburkjim 

Found some interesting points reg. AND/OR grouping elements!

There are 5 single `<L>` elements in AND groups
(36310, 37336, 45103, 59037, 72383, 80300)

and a whopping 100+ single `<L>` elements in OR groups!
(5295.1, 5963, 6230, 9218, 13040, 13046, 13293, 16421, 16441, 19425, 21437, 21529, 29168, 29633, 29831, 46491, 46738, 49740, 52477, 53475, 57080, 58684.12, 62547, 71080, 91798, 95320, 96358, 97425, 98426, 99465, 99624, 110675, 115003, 115399, 116989, 120532, 129300, 135725, 139457, 141203, 144737, 145504, 148500, 148573, 154262, 157214, 158837, 159177, 166051, 167026, 169540, 180428, 183881, 186088, 186226, 186289, 186645, 188644, 188650, 188663, 191027, 192063, 193598, 194958, 195242, 195996, 196890, 200007, 203319, 203480, 205118, 205142, 205180, 205211, 206064, 206364, 206466, 208147, 210505, 210902, 213989, 216907, 219834, 220857, 223679, 231039, 231079, 237161, 239670, 239811, 239992, 245058, 246345, 247829, 247858, 247867, 248288, 250081, 250879, 252557, 252708, 256290, 259869, 260454, 261644, 262061)

**Noticed that these are mostly with accent differences or hyphenation differences.**

**Comment by Andhrabharati** [comment] 2022-08-30 18:36
Also there are 6 `<L>` entries ending in 'or'
(1962, 9981, 96042, 156088, 169950, 171580)
and one entry with ending 'of' (**which is a typo for 'or'**)
(4074)

And there is one entry ending in 'and'
(95389)

These should be combined with the following entries appropriately and then to be made as "proper" grouped entries.

**Comment by funderburkjim** [comment] 2022-08-30 18:41
> single L groups

It seems reasonable to retain such markup, as it identifies the headwords which have more than one accent variant.

Do you have a better way to do this markup?

**Comment by Andhrabharati** [comment] 2022-08-30 19:11
There are 8 entries ending with `<ab>w.r.</ab> for`, which need to be combined with the next entries properly.
(92603, 95205, 98434, 104490, 107642, 114508, 125521, 131402)

**Comment by funderburkjim** [comment] 2022-09-01 18:07
Have handled the additional 16 'L' references mentioned in two previous comments.
See 'temp_change_or1' and 'temp_change_or2' in readme.

Handled the w.r. cases with a new info attribute:  `<info orwr="..."/>.

@Andhrabharati  Ok to close this issue?

**Comment by Andhrabharati** [comment] 2022-09-02 04:10
Speaking of ls-resolutions, you are yet to 'finally' correct the RLM as mentioned recently in the MW.

**Comment by Andhrabharati** [comment] 2022-09-02 08:37
Probably you may also consider changing the remaining [**noticed that the count has now come down to 300+ from the earlier 800+**] ṉ to ṃ; 3 of which are in the ls strings as `napuṉs.` and the remaining in the main text at the s1, ns or ab (expansion) strings.

[The single Zend etym-entry `aiwyāoṉhana` at `<L>19258.1` may also be changed as above, as this language is considered as a sister language to Sanskrit.]

**Comment by Andhrabharati** [comment] 2022-09-02 09:00
Noticed ~300 **â** instances, which should've been **à** within the 100+ `<s>` strings and in the resp. meta lines.

**Comment by Andhrabharati** [comment] 2022-09-02 09:13
Talking of the caret instances above, got reminded of another issue (#107) that might also be considered in the MW spree **now**.

**Comment by Andhrabharati** [comment] 2022-09-02 13:25
There is one instance (line 295319) where √ is not followed by a space; and one instance (line 365916) where `div n="to"/>` is not preceded by the `<`.

**Comment by funderburkjim** [comment] 2022-09-02 15:24
## RLM
tooltip altered.  Good find!  (headword kAkaciYcika).

**Comment by funderburkjim** [comment] 2022-09-03 18:22
## change_6, 7, 8
About 5000 lines changed.

These address the points above starting at https://github.com/sanskrit-lexicon/MWS/issues/137#issuecomment-1235047261.

More detailed notes are found in the readme, starting at `change_6: Extended Ascii changes in ls`.

## extended ascii 
changes `â -> ā, ê -> e, î -> ī, ô -> o, û -> ū, ṉ -> ṃ`  in 3 places:
* ls elements (e.g. `<ls>Divyâd.</ls>` -> `<ls>Divyād.</ls>` 
* tooltips for mw ls: see csl-pywork revision 8af48bf (link above)
  * tooltip abbreviations need to be consistent with `<ls>` in mw.txt
* s1 elements
  For example `<s1 slp1="mAMsarohiRI">Māṉsarohiṇī</s1>` -> `<s1 slp1="mAMsarohiRI">Māṃsarohiṇī</s1>`

Note that no changes were made in the `<etym>` elements.  In particular,
`aiwyāoṉhana at <L>19258.1` was not changed.

**Comment by funderburkjim** [comment] 2022-09-03 18:32
> Noticed 300 â instances, which should've been à within the 100+ \<s> strings and in the corresp. meta lines.

I'm not sure what was intended here --  


Here's latest iast version of mw digitization: [temp_mw_issue137_iast_rev2.zip](https://github.com/sanskrit-lexicon/MWS/files/9483181/temp_mw_issue137_iast_rev2.zip)

**Comment by funderburkjim** [comment] 2022-09-03 18:38
## paren-bracket 
Recently noticed many (800+) instances  of `([X])`.  I think @Andhrabharati previously also noticed these as needing change.  From a small sample examination of print,  I concluded these should be changed to `[X]`, See change_8.txt for these changes.

This ends my remarks regarding change_6 through change_8.

**Comment by Andhrabharati** [comment] 2022-09-03 18:56
Glad that you are considering my above suggestions, @funderburkjim !

Looking at the mwauth corrections-

![image](https://user-images.githubusercontent.com/75209130/188284008-e29eae88-f054-48d9-8a79-23fe8b4ebf8e.png)

**I  think a good revision/re-look/vetting of all the ls-expansions is required sometime sooner.** [I was just looking at the ? marked (or unlisted) ls-entries thus far in MW.]

As a glaring example, the Gaṇaratnāv. is not Gaṇaratnamahodadhi, but is Gaṇaratnāvalī!!

It is the "collection of Gaṇas to Pāṇini's gr. based on Gaṇaratnamahodadhi & other gr. & lex. works; composed in 1874 A. D. by Yajñeśvara Bhaṭṭa".

Should this be done now, or after completing the PWG ls-exercise?

**Comment by Andhrabharati** [comment] 2022-09-03 18:58
> I think @Andhrabharati previously also noticed these as needing change.

Yes, I had mentioned this earlier.

**Comment by Andhrabharati** [comment] 2022-09-03 19:09
> > Noticed 300 â instances, which should've been à within the 100+ `<s>` strings and in the corresp. meta lines.
> 
> I'm not sure what was intended here --
> 
> Here's latest iast version of mw digitization: [temp_mw_issue137_iast_rev2.zip](https://github.com/sanskrit-lexicon/MWS/files/9483181/temp_mw_issue137_iast_rev2.zip)

Pl. see under `<L>550.2` in mw.txt
metaline `<k2>` **akzitavya^**
headline `<s>` **akzitavya^**

and the corresp. iast text
metaline `<k2>` **akṣitavyâ**
headline `<s>` **akṣitavyâ**</s>


Do I make sense now, @funderburkjim ?

**Comment by funderburkjim** [comment] 2022-09-04 02:26
> akzitavya^

OK, now I see your concern.  
Using mw.txt (the slp1 version), my count is slightly different: 
`114 matches for "<k2>.*?\^"`

In slp1, the spelling uses the `^` character as an accent. Which accent?  
It is svarita: [See frontmatter](https://www.sanskrit-lexicon.uni-koeln.de/scans/csldev/csldoc/build/dictionaries/prefaces/mwpref/mwpref16.html)

Next, we have the question of how to represent, in displays, this svarita accent with diacritics.
In the printed text, the svarita accent is represented by a backward 'grave' accent, and 'udatta' by a forward 'acute accent.

The Cologne displays use a representation where svarita is represented by circumflex diacritic, udAtta by acute accent diacritic, and anudAtta by grave accent diacritic.

The iast version of MW which you are referring to also used the same 'Cologne' representation.

Thus, **there is nothing that requires changing**.  Just remember that in IAST displays of MW, a Sanskrit word with circumflex-diacritic will appear in the MW text with a 'grave'-like diacritic.

**Comment by funderburkjim** [comment] 2022-09-04 02:42
## `<srs/>` and svarita

In the printed text of MW a Sanskrit word often appears with a 'circumflex' diacritic.
But this is NOT an accent.   It is a special convention (described on the same front matter page mentioned above) for representing vowel-sandhi.  See for instance, aMSAMSa
![image](https://user-images.githubusercontent.com/6393033/188294563-58330d85-bbce-49a2-be1d-d7630a935408.png)

The representation in the Cologne digitization uses the empty xml tag `<srs/>` :
`<s>aMSA<srs/>MSa</s>`

Although MW describes 4 types of circumflex (representing short+short, short + long, etc.),  the Cologne digitization does not distinguish among these types.

I have encountered a few cases where a vowel was coded with `<srs/>` but should have
been coded with svarita.  It seems likely that there are other such errors in the digitization.

**Comment by funderburkjim** [comment] 2022-09-04 02:45
> good revision/re-look/vetting of all the ls-expansions 

Definitely agree.  You are the best person to do this.  You could
edit the file [tooltip.txt](https://github.com/sanskrit-lexicon/csl-pywork/blob/master/v02/distinctfiles/mw/pywork/mwauth/tooltip.txt) and give me
the resulting edited file for installation.
Agree best to make another issue devoted to discussions arising during the review.

**Comment by Andhrabharati** [comment] 2022-09-04 05:00
> Thus, **there is nothing that requires changing**.

I would say otherwise-- There definitely is a need to do something here!

One year ago, (April 2021) while I was at MW work (for Cologne), these were all **à** in the metalines and the resp. headlines.

To make you see the difference more clearly, I am giving two examples now (comparing MW and PWG/pwk)--

1. display of the entry **asurya** in MW

![image](https://user-images.githubusercontent.com/75209130/188297897-90bfb2d4-9cef-469e-9dd1-f2b65f39f131.png)

vs. PWG & pwk

![image](https://user-images.githubusercontent.com/75209130/188298000-488fbe0a-12b3-4e84-8ad4-43287dddeb04.png)

2. Display of  **akṣitavya** in MW

![image](https://user-images.githubusercontent.com/75209130/188298051-f5e979c3-8bf6-449e-b05c-1e995a2b73f2.png)

vs. pwkvn

![image](https://user-images.githubusercontent.com/75209130/188298092-e40f468f-76a8-40ab-a301-898497cf9739.png)


We don't have to reiterate that much of MW content is based on PWG family data, and they **should** be rendered in a similar fashion.

**Comment by Andhrabharati** [comment] 2022-09-04 08:00
> As a glaring example, the Gaṇaratnāv. is not Gaṇaratnamahodadhi, but is Gaṇaratnāvalī!!
> 
> It is the "collection of Gaṇas to Pāṇini's gr. based on Gaṇaratnamahodadhi & other gr. & lex. works; composed in 1874 A. D. by Yajñeśvara Bhaṭṭa".

Just for info--
This work got printed after 100 years, in 1986.

Here is the title page and the list of works referred--
![image](https://user-images.githubusercontent.com/75209130/188303561-be3aa61c-ee36-4dcb-9814-ba3466b1ecec.png)

![image](https://user-images.githubusercontent.com/75209130/188303575-28629d4e-aa70-4bb8-a18c-ba2bf471fe41.png)

[Probably @gasyoun might be interested to make a note of this info.]

**Comment by Andhrabharati** [comment] 2022-09-04 15:41
@funderburkjim 

Let's close this misc. corrections issue now, with another small correction-

`<div n="to"/><ab>[A-Z]` (1100+ instances) as
`<div n="vp"/><ab>[A-Z]` (2000+ instances presently),
 as all these denote **vp** type entities.

[We can handle the remaining misc. corrections in another issue sometime later.]

**Comment by funderburkjim** [comment] 2022-09-04 16:59
## pwkvn iast accent
Note IAST output for akzitavya^ in pwkvn:
![image](https://user-images.githubusercontent.com/6393033/188324772-d19effe8-99a4-4783-915f-0c451ab4080f.png)

And in mw:
![image](https://user-images.githubusercontent.com/6393033/188324806-fa45ec26-d5b4-429e-bf76-a11e56109838.png)

Note the accent representation is the same in IAST.

**Comment by funderburkjim** [comment] 2022-09-04 17:10
## pwkvn Devanagari accent

For pwkvn:
![image](https://user-images.githubusercontent.com/6393033/188324979-02a56215-e548-4c3a-8e3a-4635b41c8936.png)

For MW:
![image](https://user-images.githubusercontent.com/6393033/188324909-7bc5e060-76ad-4aa3-ad1a-a0a1bc52d33e.png)

Note the Devanagari representation for svarita accent DIFFERS in MW and in pwkvn.

## why the difference?
We have CHOSEN to make the Devanagari accent representation in PW, PWK, PWG consistent with the printed form of PWG, etc.  Thus, the little vertical line over the vowel is used to represent svarita accent in PW, etc.  (Similarly, udAtta is the little superscript devanagari 'u' in PW, etc.)

If you are wanting to compare MW with PW in terms of accents, then you should use either the slp1 representation or the IAST representation.

I still say no change is warranted at this time.  If (as I suspect) you still disagree,  I suggest you open a new issue devoted to this subject.

**Comment by Andhrabharati** [comment] 2022-09-04 17:17
I doubt if you would be correcting these, under a new issue, when not convinced about the point here itself; so I do not want to go that way.

If you don't like to bring these 100+ cases within MW in line with the rest of 127k+ cases, which are all **à** in the print, you're the final judge as far as cologne data is concerned.

**Thus, I leave the matter for now.**

**Comment by funderburkjim** [comment] 2022-09-04 21:39
>  the rest of 127k+ cases (à), which are all à in the print, 

126895 matches in 118274 lines for "a/"   These are the instances (according to Cologne digitization) of the short vowel 'a' with udAtta accent.
These are represented in print with an acute accent (e.g., under headword 'a'):
![image](https://user-images.githubusercontent.com/6393033/188334432-bb991baf-13ac-4b44-8431-0df6e7d4131f.png)

And, with output=iast in a Cologne display, they appear as a-with-acute-accent, á, not à
![image](https://user-images.githubusercontent.com/6393033/188334489-385af30c-a201-42c0-8ec5-3cc4da958706.png)

The a with grave accent (à) would be the Cologne iast representation of "a with anudAtta accent" (slp1 `a\`),   - there are none of these in MW.

**Comment by funderburkjim** [comment] 2022-09-04 22:19
Although I don't feel comfortable with changing  the representation of svarita accent in Cologne mw displays,  I'm not sure my view should prevail.  I've opened another issue so the question of accent representation (especially in mw and in the PW family of dictionaries) will remain 'open' for some future consideration.

**Comment by funderburkjim** [comment] 2022-09-04 22:32
## 3rd batch of changes
These mainly from above https://github.com/sanskrit-lexicon/MWS/issues/137#issuecomment-1236366820.

Also corrected several 'madA' entries to 'mada' -- some 'sub-entries' of 'mada' were incorrectly interpreted as feminine.  

The details are in change_9.txt file of issue137 directory, and also mentioned in the readme at 'change_9' and following.

Here is the latest iast version of mw: 
[temp_mw_issue137_iast_rev3.zip](https://github.com/sanskrit-lexicon/MWS/files/9485614/temp_mw_issue137_iast_rev3.zip)

Many varied improvements now made to the mw digitization and markup. 
Thanks to @Andhrabharati for his continued 'fresh look' at mw.
Now closing the issue.

**Closed by funderburkjim** 2022-09-04 22:32 UTC

**Comment by Andhrabharati** [comment] 2022-09-05 01:49
> > the rest of 127k+ cases (à), which are all à in the print,
> 


**It is my grosss mistake, using a wrong character at this.**

**Comment by funderburkjim** [comment] 2022-09-19 17:36
## accent revision

[temp1_mw_10_iast.zip](https://github.com/sanskrit-lexicon/MWS/files/9601092/temp1_mw_10_iast.zip)

This is iast version of mw digitization, with accent revised (so svarita accent = grave accent diacritic).
For discussion, refer #140.

**Comment by Andhrabharati** [comment] 2022-09-19 17:59
Fantastic; **now the CDSL MW Roman text matches with the print.**

Thanks a lot for relieving my worry, @funderburkjim !

As MW does not mark the Devanagari accents in the book, I am not that bothered about them in MW display and would leave the matter to the discretion of Jim, whether to match MW with PWG family or not.

However my final comment on the matter is to ask the team (@funderburkjim  & @gasyoun) to just check the MW RV citations once with the corresponding linked RV text (courtesy: Marcis) and see if they notice **any differences in Devanagari accents**, and then compare the PWG RV citations with the RV links thereupon. [Probably, my point would be appreciated then.]
